<?php
// Key: Index
// Value: Sum of calories
function parse_into_map($in)
{
    $in = str_replace("\n", "-", $in); // separate all values
    $in = str_replace("--", ",", $in); // separate elves
    $in = rtrim($in, "-"); // delete last character generated by str_replace
    $arr = explode(",", $in); // split elves by ","
    $len = count($arr);
    $map = [];
    for ($i = 0; $i < $len; $i++)
    {  
        $values = array_map('intval', explode("-", $arr[$i]));
        $calories_sum = array_sum($values);
        $map[$i] = $calories_sum;
    }
    arsort($map); // sort map descending
    return $map;
}

function part1($in)
{
    $map = parse_into_map($in);
    $it = (new ArrayObject($map))->getIterator(); // iterator is needed because I sorted the map without changing the keys
    $out = $it->current();
    echo "Part 1: $out\n";
}

function part2($in)
{
    $map = parse_into_map($in);
    $it = (new ArrayObject($map))->getIterator();
    $sum = $it->current();
    for ($i = 0; $i < 2; $i++)
    {
        $it->next();
        $sum += $it->current();
    }
    echo "Part 2: $sum";
}

$in = file_get_contents("./inputs/1.txt");
part1($in);
part2($in);
